#' Example data for the background process
#'
#' An example of the background data generated by mixture of 2 Gaussian components with equal proportions. Component parameters are specified
#' in detail in vignette (run ) The data is used to train a model to find anomalies in the experimental data
#'
#'
#' @docType data
#' @keywords datasets
#' @name bcg_data
#' @usage data(bcg_data)
#' @format A dataset of 500 observations with 16 variables
#' @references Working paper on a Statistical Learning method for Model-Independent searches for New Physics - AMVA4NewPhysics ITN
NULL

#' Example data for the experimental data containing an unknown signal observations
#'
#' An example of the experimental data generated by mixture background process and a signal process with
#' proportion equal to 10\%. The data could be used jointly with the background data to train a model and find anomalies in the data
#' at hand with respect to the background data.
#'
#'
#'
#' @docType data
#' @keywords datasets
#' @name experiment_data
#' @usage data(experiment_data)
#' @format A dataset of 500 observations with 16 variables
#' @references Working paper on a Statistical Learning method for Model-Independent searches for New Physics - AMVA4NewPhysics ITN
NULL
